//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fit5120.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV
    {
        public int Id { get; set; }
        public long UV_Value { get; set; }
        public long Forecast_value { get; set; }
    }
}
